kube_prometheus_stack_chart_version: 45.9.1
prometheus_node_exporter_hostRootFsMount: true
kube_prometheus_stack_values: 
  prometheus:
    remoteWriteDashboards: true
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: "{{ prometheus_node_exporter_hostRootFsMount }}"
  grafana:
    defaultDashboardsTimezone: Europe/Berlin