---
grafana_chart_version: 8.10.4

grafana_values:

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/"

  ingress:
    enabled: true
    ingressClassName: public
    annotations:
      cert-manager.io/cluster-issuer: "{{ cert_manager_cluster_issuer_name }}"
    hosts:
      - "grafana.{{ domain_name }}"
    path: "/"
    tls:
      - secretName: grafana-tls
        hosts:
          - "grafana.{{ domain_name }}"

  persistence:
    enabled: true
    type: pvc
    size: 100Mi

  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      folderAnnotation: grafana_folder
      provider:
        foldersFromFilesStructure: true

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: VictoriaMetrics
          type: prometheus
          access: proxy
          url: "http://vmsingle-vmstack-vmks.monitoring.svc:8428"
          isDefault: true
          editable: true
          jsonData:
            timeInterval: 30s
          prometheusType: Prometheus

# extraVolumeMounts:
#   - name: plugins
#     mountPath: /var/lib/grafana/plugins
#     subPath: configs/grafana/plugins
#     readOnly: false
#   - name: dashboards
#     mountPath: /var/lib/grafana/dashboards
#     hostPath: /usr/shared/grafana/dashboards
#     readOnly: false

# extraVolumes:
#   - name: plugins
#     existingClaim: existing-grafana-claim
#   - name: dashboards
#     persistentVolumeClaim: grafana-dashboards
