---
home_assistant_chart_version: 0.3.32

home_assistant_values:
  controller:
    type: StatefulSet
  persistence:
    enabled: true
    size: 1Gi
    annotations:
      k8up.io/backup: "true"
  additionalVolumes:
    - hostPath:
        path: >-
          /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2695656-if00
        type: CharDevice
      name: zigbee
  additionalMounts:
    - mountPath: /dev/ttyACM0
      name: zigbee
  ingress:
    enabled: true
    external: false
    annotations:
      cert-manager.io/cluster-issuer: "{{ cert_manager_cluster_issuer_name }}"
    hosts:
      - host: "hass.{{ domain_name }}"
        paths:
          - path: "/"
            pathType: Prefix
    tls:
      - secretName: home-assistant-tls
        hosts:
          - "hass.{{ domain_name }}"
  hostPort:
    enabled: true
    port: 8124
  securityContext:
    privileged: true
  serviceMonitor:
    enabled: false
    scrapeInterval: 60s
  env:
    - name: MY_TIME_ZONE
      value: "Europe/Berlin"
  configuration:
    enabled: true
    forceInit: true
    trusted_proxies:
      - 10.0.0.0/8

