---
# renovate: helm-chart=home-assistant registryUrl=https://pajikos.github.io/home-assistant-helm-chart/
home_assistant_chart_version: 0.3.66

home_assistant_values:

  controller:
    type: StatefulSet

  persistence:
    enabled: true
    size: 1Gi
    annotations:
      k8up.io/backup: "true"

  additionalVolumes:
    - hostPath:
        path: >-
          /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2695656-if00
        type: CharDevice
      name: zigbee
  additionalMounts:
    - mountPath: /dev/ttyACM0
      name: zigbee

  # ingress:
  #   enabled: true
  #   external: false
  #   annotations:
  #     cert-manager.io/cluster-issuer: "{{ cert_manager_cluster_issuer_name }}"
  #   hosts:
  #     - host: "ha.{{ domain_name }}"
  #       paths:
  #         - path: "/"
  #           pathType: Prefix
  #   tls:
  #     - secretName: home-assistant-tls
  #       hosts:
  #         - "ha.{{ domain_name }}"

  hostPort:
    enabled: true
    port: 8124
  securityContext:
    privileged: true

  serviceMonitor:
    enabled: true
    scrapeInterval: 30s

  env:
    - name: MY_TIME_ZONE
      value: "Europe/Berlin"

  configuration:
    enabled: true
    forceInit: true
    trusted_proxies:
      - 10.0.0.0/8
    templateConfig: |
      homeassistant:
        name: Home
        unit_system: metric
        currency: EUR
        language: en
        country: DE
        temperature_unit: C
        time_zone: "Europe/Berlin"
        internal_url: "http://{{ hostname }}:8124"
        external_url: "https://ha.{{ domain_name }}"

      default_config:

      http:
        use_x_forwarded_for: true
        trusted_proxies:
          - 10.0.0.0/8
        ip_ban_enabled: true
        login_attempts_threshold: 5

      frontend:
        themes: !include_dir_merge_named themes

      prometheus:
        namespace: ha
        requires_auth: false

      automation: !include automations.yaml
      script: !include scripts.yaml
      scene: !include scenes.yaml

