---
victoria_metrics_chart_version: 0.72.5

victoria_metrics_values:

  nameOverride: vmks

  # Disable Grafana because it's deployed separately via the grafana Ansible role
  grafana:
    enabled: false
    # Sidecar labels for external Grafana to pick up dashboard/datasource ConfigMaps
    sidecar:
      dashboards:
        label: grafana_dashboard
        labelValue: "1"
      datasources:
        label: grafana_datasource
        labelValue: "1"
    forceDeployDatasource: true

  defaultDashboards:
    enabled: true
    defaultTimezone: Europe/Berlin
    annotations:
      grafana_folder: "VictoriaMetrics"
    victoriametrics-vmalert:
      enabled: false

  defaultRules:
    create: true

  vmsingle:
    enabled: true
    spec:
      retentionPeriod: "1y"
      storage:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi

  vmagent:
    enabled: true
    spec:
      selectAllByDefault: true
      scrapeInterval: 30s
      externalLabels: {}

  victoria-metrics-operator:
    enabled: true
    operator:
      disable_prometheus_converter: false
      enable_converter_ownership: true # will remove corresponding victoria-metrics CRs when the prometheus ones are deleted

  alertmanager:
    enabled: false
  vmalert:
    enabled: false

  vmauth:
    enabled: false
  vmcluster:
    enabled: false
  kubeProxy:
    enabled: false
